//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Fedit.rc
//
#define IDOK_RES                        1
#define IDCLRLIB                        3
#define IDC_PREVIEW                     3
#define IDOK_CANV                       3
#define IDD_NEW                         101
#define IDD_FIEW_DIALOG                 102
#define IDS_APP_TITLE                   103
#define IDI_FIEW                        107
#define IDI_SMALL                       108
#define IDR_MAINFRAME                   128
#define IDR_DLLRAR                      128
#define IDR_MENU                        131
#define IDR_ACCELERATORS                132
#define IDR_ABOUT                       139
#define ICC_SELVER                      143
#define ICC_CRO                         144
#define ICC_DRAPEN                      145
#define ICC_MOV                         146
#define ICC_SELCIR                      147
#define ICC_SELHOR                      148
#define ICC_SELREC                      149
#define IDR_XML1                        150
#define IDR_MANIFEST                    150
#define ICC_TEX                         150
#define ICC_ZOO                         152
#define ICC_ERSNOR                      153
#define ICC_FILBUC                      154
#define ICC_HAN                         155
#define ICC_LASPOL                      156
#define ICC_MAG                         157
#define ICC_SMPCOL                      158
#define ICC_SHALIN                      159
#define IDD_CLR                         160
#define IDD_RES                         161
#define ICC_VECDRA                      163
#define ICC_VECSEL                      164
#define IDC_TXTULN                      165
#define IDC_TXTBLD                      166
#define IDC_TXTITA                      167
#define ITC_NEW                         168
#define ICC_COLRES                      169
#define ICC_COLSWA                      170
#define ITC_DEL                         171
#define IDD_FIL                         172
#define ITC_DOWN                        173
#define ITC_UP                          174
#define ICC_SHARRC                      175
#define ICC_SHACIR                      176
#define ICC_SHAREC                      177
#define ICC_LASMOS                      178
#define IDD_IMG                         179
#define IDC_RADIO1                      998
#define IDC_RADIO2                      999
#define IDC_EDIT_NAME                   1000
#define IDC_COMBO_PRESET                1001
#define IDC_COMBO_WUNIT                 1002
#define IDC_COMBO_HUNIT                 1003
#define IDC_COMBO_RUNIT                 1004
#define IDC_COMBO_DUNIT                 1005
#define IDC_EDIT_W                      1006
#define IDC_EDIT_R                      1007
#define IDC_EDIT_H                      1008
#define IDC_COMBO_DMODE                 1009
#define IDC_COMBO_BKGND                 1010
#define IDC_ABORT                       1012
#define IDC_SAVEPRES                    1013
#define IDC_DELPRES                     1014
#define IDC_SLIDER1                     1017
#define IDC_SLIDER                      1017
#define IDC_CLRFIELD                    1018
#define IDC_CLRSLID                     1019
#define IDC_CLRCMP                      1020
#define IDC_RB_H                        1021
#define IDC_RB_S                        1022
#define IDC_RB_V                        1023
#define IDC_RB_R                        1024
#define IDC_RB_G                        1025
#define IDAUTO                          1025
#define IDC_RB_B                        1026
#define IDC_EDIT_PXWIDTH                1026
#define IDC_RB_L                        1027
#define IDC_EDIT_PXHEIGHT               1027
#define IDC_RB_A                        1028
#define IDC_COMBO_PXWIDTH               1028
#define IDC_RB_LAB                      1029
#define IDC_COMBO_PXHEIGHT              1029
#define IDC_V_H                         1030
#define IDC_EDIT_WIDTH                  1030
#define IDC_V_S                         1031
#define IDC_EDIT_HEIGHT                 1031
#define IDC_V_V                         1032
#define IDC_COMBO_WIDTH                 1032
#define IDC_V_R                         1033
#define IDC_COMBO_HEIGHT                1033
#define IDC_V_G                         1034
#define IDC_EDIT_RES                    1034
#define IDC_V_B                         1035
#define IDC_COMBO_RES                   1035
#define IDC_V_HEX                       1036
#define IDC_CHECK_STYLES                1036
#define IDC_V_L                         1037
#define IDC_CHECK_CONST                 1037
#define IDC_V_A                         1038
#define IDC_CHECK_RESAMPLE              1038
#define IDC_V_LAB                       1039
#define IDC_COMBO_RESAMPLE              1039
#define IDC_V_C                         1040
#define IDC_THUMB                       1040
#define IDC_V_M                         1041
#define IDC_EDIT1                       1041
#define IDC_V_Y                         1042
#define IDC_EDIT2                       1042
#define IDC_V_K                         1043
#define IDC_EDIT3                       1043
#define IDC_EDIT4                       1044
#define IDC_EDIT5                       1045
#define IDC_EDIT6                       1046
#define IDC_EDIT7                       1047
#define IDC_EDIT8                       1048
#define IDC_EDIT9                       1049
#define IDC_EDIT10                      1050
#define IDC_EDIT11                      1051
#define IDC_EDIT12                      1052
#define IDC_EDIT13                      1053
#define IDC_EDIT14                      1054
#define IDC_EDIT15                      1055
#define IDC_EDIT16                      1056
#define IDC_EDIT17                      1057
#define IDC_EDIT18                      1058
#define IDC_EDIT19                      1059
#define IDC_EDIT20                      1060
#define IDC_EDIT21                      1061
#define IDC_EDIT22                      1062
#define IDC_EDIT23                      1063
#define IDC_EDIT24                      1064
#define IDC_EDIT25                      1065
#define IDC_STATIC_NAME                 1066
#define IDC_VALUE                       1067
#define IDC_STATIC_GROUP                1068
#define IDC_CHECK_BW                    1069
#define IDC_STATIC_VALUELABEL           1070
#define IDC_CHECK_PREV                  1071
#define IDC_CHECK_BWA                   1071
#define IDOK2                           1075
#define IDOKI                           1075
#define ID_FILE_OPEN                    32771
#define ID_FILE_OPENFOLDER              32772
#define ID_FILE_CLOSE                   32773
#define ID_FILE_EXTRACT                 32774
#define ID_FILE_EXIT                    32775
#define ID_VIEW_FULLSCREEN              32776
#define ID_VIEW_THUMBNAILS              32777
#define ID_VIEW_LIST                    32778
#define ID_VIEW_FITTO                   32779
#define ID_FITTO_SCREEN                 32780
#define ID_FITTO_WIDTH                  32781
#define ID_FITTO_HEIGHT                 32782
#define ID_FITTO_NUMPAD                 32783
#define ID_VIEW_RESIZE                  32784
#define ID_RESIZE_100                   32785
#define ID_RESIZE_75                    32786
#define ID_RESIZE_50                    32787
#define ID_RESIZE_25                    32788
#define ID_RESIZE_200                   32789
#define ID_RESIZE_300                   32790
#define ID_RESIZE_500                   32791
#define ID_RESIZE_ZOOMIN                32792
#define ID_RESIZE_ZOOMOUT               32793
#define ID_VIEW_ROTATE                  32794
#define ID_ROTATE_RESET                 32795
#define ID_ROTATE_90                    32796
#define ID_ROTATE_180                   32797
#define ID_ROTATE_270                   32798
#define ID_HELP_ABOUTFIEW               32799
#define ID_HELP_MANUAL                  32800
#define ID_VIEW_ZOOM                    32801
#define ID_ZOOM_100                     32802
#define ID_ZOOM_75                      32803
#define ID_ZOOM_50                      32804
#define ID_ZOOM_25                      32805
#define ID_ZOOM_200                     32806
#define ID_ZOOM_300                     32807
#define ID_ZOOM_500                     32808
#define ID_ZOOM_ZOOMIN                  32809
#define ID_ZOOM_ZOOMOUT                 32810
#define ID_VIEW_FLOWSCROLL              32824
#define ID_FITTO_LEFT                   32828
#define ID_FITTO_RIGHT                  32829
#define ID_FITTO_SCREENIFOVERSIZED      32830
#define ID_FILE_SETASWALLPAPER          32831
#define ID_WINDOW_TILEHORIZONTALLY      32832
#define ID_WINDOW_TILEVERTICALLY        32833
#define ID_WINDOW_CASCADE               32834
#define ID_WINDOW_ARRANGE               32835
#define ID_FILE_NEW                     32836
#define ID_FILE_SAVE                    32837
#define ID_FILE_SAVEAS                  32838
#define ID_EDIT                         32839
#define ID_EDIT_UNDO                    32840
#define ID_EDIT_REDO                    32841
#define ID_EDIT_CUT                     32842
#define ID_EDIT_COPY                    32843
#define ID_EDIT_COPYMERGED              32844
#define ID_EDIT_PASTE                   32845
#define ID_EDIT_PASTEINTO               32846
#define ID_EDIT_CLEAR                   32847
#define ID_EDIT_FILL                    32848
#define ID_EDIT_STROKE                  32849
#define ID_EDIT_FREETRANSFORM           32850
#define ID_IMAGE                        32851
#define ID_IMAGE_MODE                   32852
#define ID_IMAGE_ADJUSTMENTS            32853
#define ID_IMAGE_IMAGESIZE              32854
#define ID_IMAGE_CANVASSIZE             32855
#define ID_WINDOW_SHOWINFO              32856
#define ID_WINDOW_SHOWLAYERS            32857
#define ID_WINDOW_SHOWHISTORY           32858
#define ID_FILTER                       32859
#define ID_FILTER_LASTFILTER            32860
#define ID_FILTER_BLUR                  32861
#define ID_FILTER_GAUSSIANBLUR          32862
#define ID_FILTER_SHARPEN               32863
#define ID_FILTER_EDGETRACE             32864
#define ID_FILTER_EMBOSS                32865
#define ID_EMBOSS_EAST                  32866
#define ID_EMBOSS_SOUTH                 32867
#define ID_EMBOSS_SOUTH32868            32868
#define ID_FILTER_HIGHLIGHT             32869
#define ID_FILTER_DEFOCUS               32870
#define ID_FILTER_OLDSTONE              32871
#define ID_FILTER_CUSTOM                32872
#define ID_EMBOSS_SOUTHEAST             32873
#define ID_SELECT                       32874
#define ID_SELECT_SELECTALL             32875
#define ID_SELECT_DESELECT              32876
#define ID_SELECT_INVERSESELECTION      32877
#define ID_LAYER                        32878
#define ID_LAYER_ADD                    32879
#define ID_LAYER_DELETE                 32880
#define ID_LAYER_MOVEUP                 32881
#define ID_LAYER_MOVEDOWN               32882
#define ID_LAYER_MERGEDOWN              32883
#define ID_LAYER_RASTERIZE              32884
#define ID_LAYER_VISIBLE                32885
#define ID_LAYER_LOCKED                 32886
#define ID_ROTATE_90CW                  32887
#define ID_ROTATE_90CCW                 32888
#define ID_ROTATE_181                   32889
#define ID_TRANSFORM_ROTATE90CW         32890
#define ID_ROTATE_90CW32891             32891
#define ID_ROTATE_90CCW32892            32892
#define ID_ROTATE_182                   32893
#define ID_TRANSFORM_FLIP               32894
#define ID_FLIP_HORIZONTALLY            32895
#define ID_FLIP_VERTICALLY              32896
#define ID_FILE_SAVEOPTIMAZED           32897
#define ID_FILE_SAVEOPTIMIZED           32898
#define ID_EDIT_ROTATE_90CW             32899
#define ID_EDIT_ROTATE_90CCW            32900
#define ID_EDIT_ROTATE_180              32901
#define ID_WINDOW_FULLSCREEN            32912
#define ID_WINDOW_ARRANGETOOLS          32913
#define ID_LAYER_RASTER                 32927
#define ID_LAYER_EDITTEXT               32930
#define ID_FILE_CLOSEALL                32932
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32933
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
